# ruff: noqa: N815 (camelCase class attributes are an Orionis convention)
from __future__ import annotations
from datetime import UTC, datetime
from typing import TYPE_CHECKING, Any, ClassVar
from orionis.orm.attributes import AttributesMixin, serializeForStorage
from orionis.orm.metaclass import ModelMeta
from orionis.orm.query.builder import ModelQueryBuilder
from orionis.orm.query.expressions import (
    DeletePlan,
    InsertPlan,
    UpdatePlan,
    WhereClause,
)
from orionis.orm.schema.types import ColumnType
from orionis.orm.state import StateMixin

if TYPE_CHECKING:
    from orionis.orm.collections.paginator import Paginator  # noqa: F401
    from orionis.orm.metaclass import ModelMetadata
    from orionis.support.types.collection import Collection

# Instance slots managed directly by the model machinery.
_INTERNAL_ATTRIBUTES: frozenset[str] = frozenset({
    "_attributes",
    "_changes",
    "_exists",
    "_original",
})


class Model(AttributesMixin, StateMixin, metaclass=ModelMeta):
    """
    Base class of the Orionis active-record models.

    Concrete models declare their columns with the fluent schema types
    and interact with the database exclusively through the Orionis query
    builder; the underlying SQL engine never surfaces. Class-level entry
    points such as ``where`` or ``orderBy`` start a builder implicitly.
    """

    __abstract__ = True
    __slots__ = ("_attributes", "_changes", "_exists", "_original")

    # ── Declarative configuration ───────────────────────────────────────────

    # Logical table name; derived from the class name when None.
    table: ClassVar[str | None] = None

    # Named connection; the default connection is used when None.
    connection: ClassVar[str | None] = None

    # Mass assignment whitelist; every column is fillable when empty.
    fillable: ClassVar[list[str]] = []

    # Mass assignment blacklist; supports the "*" wildcard.
    guarded: ClassVar[list[str]] = []

    # Attributes omitted from serialization.
    hidden: ClassVar[list[str]] = []

    # Attribute casts applied on hydration and assignment.
    casts: ClassVar[dict[str, str]] = {}

    # Primary key name; discovered from column flags when None.
    primaryKey: ClassVar[str | None] = None

    # Whether the primary key is generated by the database.
    incrementing: ClassVar[bool] = True

    # Whether creation/update timestamps are maintained automatically.
    timestamps: ClassVar[bool] = True

    # Timestamp column names, overridable per model.
    CREATED_AT: ClassVar[str] = "created_at"
    UPDATED_AT: ClassVar[str] = "updated_at"

    # Metadata attached by the metaclass.
    __meta__: ClassVar[ModelMetadata | None]

    def __init__(self, attributes: dict[str, Any] | None = None) -> None:
        """
        Initialize a new, unsaved model instance.

        Parameters
        ----------
        attributes : dict or None, optional
            Attributes to mass assign honoring the fillable rules.

        Returns
        -------
        None
            This method does not return a value.

        Raises
        ------
        MassAssignmentException
            If an attribute violates the mass assignment rules.
        """
        object.__setattr__(self, "_attributes", {})
        object.__setattr__(self, "_original", {})
        object.__setattr__(self, "_changes", {})
        object.__setattr__(self, "_exists", False)
        if attributes:
            self.fill(attributes)

    # ── Attribute access ────────────────────────────────────────────────────

    def __getattr__(self, key: str) -> Any:  # noqa: ANN401
        """
        Serve column values from the attribute store.

        Parameters
        ----------
        key : str
            Attribute name being accessed.

        Returns
        -------
        Any
            Attribute value; ``None`` for declared but unloaded columns.

        Raises
        ------
        AttributeError
            If the name is neither loaded nor a declared column.
        """
        # Internal names reaching here mean the instance is mid-construction.
        if key.startswith("_"):
            error_msg = (
                f"'{type(self).__name__}' object has no attribute '{key}'"
            )
            raise AttributeError(error_msg)

        attributes = object.__getattribute__(self, "_attributes")
        if key in attributes:
            return attributes[key]

        meta = type(self).__meta__
        if meta is not None and key in meta.columns:
            return None

        error_msg = (
            f"'{type(self).__name__}' object has no attribute '{key}'"
        )
        raise AttributeError(error_msg)

    def __setattr__(self, key: str, value: Any) -> None:  # noqa: ANN401
        """
        Route column assignments into the attribute store.

        Parameters
        ----------
        key : str
            Attribute name being assigned.
        value : Any
            Value to assign.

        Returns
        -------
        None
            This method does not return a value.
        """
        if key in _INTERNAL_ATTRIBUTES:
            object.__setattr__(self, key, value)
            return

        meta = type(self).__meta__
        if meta is not None and key in meta.columns:
            self.setAttribute(key, value)
            return

        object.__setattr__(self, key, value)

    def __repr__(self) -> str:
        """
        Return a concise developer representation of the model.

        Returns
        -------
        str
            Representation including the class name and primary key.
        """
        meta = type(self).__meta__
        key = meta.primaryKey if meta is not None else "id"
        return (
            f"<{type(self).__name__} {key}={self._attributes.get(key)!r}>"
        )

    # ── Hydration ───────────────────────────────────────────────────────────

    @classmethod
    def _newFromDatabase(cls, row: dict[str, Any]) -> Model:
        """
        Hydrate a model instance from a database row.

        Parameters
        ----------
        row : dict
            Raw row values keyed by column name.

        Returns
        -------
        Model
            Existing model instance with casts applied.
        """
        instance = cls.__new__(cls)
        attributes = cls.__meta__.applyCasts(dict(row))
        object.__setattr__(instance, "_attributes", attributes)
        object.__setattr__(instance, "_original", dict(attributes))
        object.__setattr__(instance, "_changes", {})
        object.__setattr__(instance, "_exists", True)
        return instance

    # ── Query entry points ──────────────────────────────────────────────────

    @classmethod
    def query(cls) -> ModelQueryBuilder[Any]:
        """
        Start a new query builder bound to this model.

        Returns
        -------
        ModelQueryBuilder
            Fresh builder targeting the model table.
        """
        return ModelQueryBuilder(cls)

    @classmethod
    async def all(cls) -> Collection:
        """
        Retrieve every row of the model table.

        Returns
        -------
        Collection
            Collection of hydrated model instances.
        """
        return await cls.query().get()

    @classmethod
    async def find(cls, key: Any) -> Model | None:  # noqa: ANN401
        """
        Retrieve a model by its primary key.

        Parameters
        ----------
        key : Any
            Primary key value to look up.

        Returns
        -------
        Model or None
            Matching model, or ``None`` when absent.
        """
        return await cls.query().find(key)

    @classmethod
    async def findOrFail(cls, key: Any) -> Model:  # noqa: ANN401
        """
        Retrieve a model by primary key or raise when absent.

        Parameters
        ----------
        key : Any
            Primary key value to look up.

        Returns
        -------
        Model
            Matching model.

        Raises
        ------
        ModelNotFoundException
            If no record matches the key.
        """
        return await cls.query().findOrFail(key)

    @classmethod
    async def first(cls) -> Model | None:
        """
        Retrieve the first row of the model table.

        Returns
        -------
        Model or None
            First model, or ``None`` when the table is empty.
        """
        return await cls.query().first()

    @classmethod
    async def firstOrFail(cls) -> Model:
        """
        Retrieve the first row or raise when the table is empty.

        Returns
        -------
        Model
            First model.

        Raises
        ------
        ModelNotFoundException
            If the table has no rows.
        """
        return await cls.query().firstOrFail()

    @classmethod
    async def create(cls, attributes: dict[str, Any]) -> Model:
        """
        Create, persist, and return a new model.

        Parameters
        ----------
        attributes : dict
            Attributes to mass assign honoring the fillable rules.

        Returns
        -------
        Model
            Persisted model instance.

        Raises
        ------
        MassAssignmentException
            If an attribute violates the mass assignment rules.
        QueryException
            If the insert statement fails.
        """
        instance = cls(attributes)
        await instance.save()
        return instance

    @classmethod
    async def destroy(cls, *keys: Any) -> int:  # noqa: ANN401
        """
        Delete the models matching the given primary keys.

        Parameters
        ----------
        *keys : Any
            Primary key values to delete.

        Returns
        -------
        int
            Number of deleted rows.
        """
        if not keys:
            return 0
        return await cls.query().whereIn(cls.__meta__.primaryKey, keys).delete()

    # ── Persistence ─────────────────────────────────────────────────────────

    async def save(self) -> bool:
        """
        Persist the model, inserting or updating as appropriate.

        New models are inserted, receiving their generated primary key;
        existing models write only their dirty attributes. Timestamps
        are maintained automatically when enabled.

        Returns
        -------
        bool
            ``True`` when the operation succeeds or nothing changed.

        Raises
        ------
        QueryException
            If the statement fails to execute.
        """
        if self._exists:
            return await self._performUpdate()
        return await self._performInsert()

    async def update(self, attributes: dict[str, Any]) -> bool:
        """
        Mass assign the given attributes and persist the model.

        Parameters
        ----------
        attributes : dict
            Attributes to assign honoring the fillable rules.

        Returns
        -------
        bool
            ``True`` when the operation succeeds or nothing changed.

        Raises
        ------
        MassAssignmentException
            If an attribute violates the mass assignment rules.
        QueryException
            If the statement fails to execute.
        """
        self.fill(attributes)
        return await self.save()

    async def delete(self) -> bool:
        """
        Delete the model row from the database.

        Returns
        -------
        bool
            ``True`` when a row was deleted, ``False`` for unsaved
            models.

        Raises
        ------
        QueryException
            If the statement fails to execute.
        """
        if not self._exists:
            return False

        meta = type(self).__meta__
        key = meta.primaryKey
        plan = DeletePlan(
            table=meta.table,
            wheres=[WhereClause(column=key, value=self._primaryKeyValue())],
        )
        deleted = await self.query()._connection().delete(plan)  # noqa: SLF001
        self._exists = False
        return deleted > 0

    # ── Timestamps ──────────────────────────────────────────────────────────

    @classmethod
    def freshTimestamp(cls) -> datetime:
        """
        Produce the current timestamp for persistence operations.

        Timezone-aware timestamps are produced when the update column
        is a timezone-aware type, naive UTC otherwise.

        Returns
        -------
        datetime
            Current UTC timestamp.
        """
        now = datetime.now(UTC)
        meta = cls.__meta__
        target = meta.updatedColumn or meta.createdColumn
        if target is not None:
            column = meta.columns.get(target)
            aware = column is not None and (
                column.column_type is ColumnType.TIMESTAMP
            )
            if not aware:
                return now.replace(tzinfo=None)
        return now

    # ── Internal persistence helpers ────────────────────────────────────────

    def _primaryKeyValue(self) -> Any:  # noqa: ANN401
        """
        Return the primary key value identifying the stored row.

        The original value is preferred so a dirty primary key still
        targets the persisted row.

        Returns
        -------
        Any
            Primary key value.
        """
        key = type(self).__meta__.primaryKey
        if key in self._original:
            return self._original[key]
        return self._attributes.get(key)

    async def _performInsert(self) -> bool:
        """
        Insert the model attributes as a new row.

        Returns
        -------
        bool
            ``True`` when the insert succeeds.

        Raises
        ------
        QueryException
            If the statement fails to execute.
        """
        meta = type(self).__meta__

        # Maintain creation and update timestamps on first persist.
        if meta.createdColumn and meta.createdColumn not in self._attributes:
            self._attributes[meta.createdColumn] = self.freshTimestamp()
        if meta.updatedColumn and meta.updatedColumn not in self._attributes:
            self._attributes[meta.updatedColumn] = self.freshTimestamp()

        values = serializeForStorage(meta, dict(self._attributes))
        plan = InsertPlan(table=meta.table, values=[values])
        result = await self.query()._connection().insert(plan)  # noqa: SLF001

        # Adopt the database-generated primary key.
        generated = result.lastInsertId
        if meta.incrementing and generated is not None:
            self._attributes[meta.primaryKey] = generated

        self._exists = True
        self._changes = dict(self._attributes)
        self.syncOriginal()
        return True

    async def _performUpdate(self) -> bool:
        """
        Write the dirty attributes of an existing model.

        Returns
        -------
        bool
            ``True`` when a row was written or nothing changed,
            ``False`` when no stored row matched the primary key.

        Raises
        ------
        QueryException
            If the statement fails to execute.
        """
        dirty = self.getDirty()
        if not dirty:
            self._changes = {}
            return True

        meta = type(self).__meta__

        # Refresh the update timestamp alongside the dirty attributes.
        if meta.updatedColumn and meta.updatedColumn not in dirty:
            timestamp = self.freshTimestamp()
            self._attributes[meta.updatedColumn] = timestamp
            dirty[meta.updatedColumn] = timestamp

        plan = UpdatePlan(
            table=meta.table,
            values=serializeForStorage(meta, dirty),
            wheres=[
                WhereClause(
                    column=meta.primaryKey,
                    value=self._primaryKeyValue(),
                ),
            ],
        )
        affected = await self.query()._connection().update(plan)  # noqa: SLF001

        self._changes = dict(dirty)
        self.syncOriginal()
        return affected > 0
