name: Orionis Framework - Test Suite

on:
  push:
    branches:
      - 1.x
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🦀 Install uv
        uses: astral-sh/setup-uv@v3

      - name: 🐍 Set Python Version
        run: uv python install 3.14

      - name: 📦 Sync Dependencies
        run: uv sync

      - name: 🐇 Run Tests Aio [tests/aio]
        run: |
          uv run ruff check ./orionis/aio/ --statistics
          uv run python -B reactor test --start-dir="tests/aio" --verbosity=1 --fail-fast=1

      - name: ⏳ Run Tests Background [tests/background]
        run: |
          uv run ruff check ./orionis/background/ --statistics
          uv run python -B reactor test --start-dir="tests/background" --verbosity=1 --fail-fast=1

      - name: 💾 Run Tests Cache [tests/cache]
        run: |
          uv run ruff check ./orionis/cache/ --statistics
          uv run python -B reactor test --start-dir="tests/cache" --verbosity=1 --fail-fast=1

      - name: 🖥️ Run Tests Console [tests/console]
        run: |
          uv run ruff check ./orionis/console/ --statistics
          uv run python -B reactor test --start-dir="tests/console" --verbosity=1 --fail-fast=1

      - name: 📦 Run Tests Container [tests/container]
        run: |
          uv run ruff check ./orionis/container/ --statistics
          uv run python -B reactor test --start-dir="tests/container" --verbosity=1 --fail-fast=1

      - name: 🔐 Run Tests Encrypter [tests/encrypter]
        run: |
          uv run ruff check ./orionis/encrypter/ --statistics
          uv run python -B reactor test --start-dir="tests/encrypter" --verbosity=1 --fail-fast=1

      - name: 🌿 Run Tests Environment [tests/environment]
        run: |
          uv run ruff check ./orionis/environment/ --statistics
          uv run python -B reactor test --start-dir="tests/environment" --verbosity=1 --fail-fast=1

      - name: 🚨 Run Tests Failure [tests/failure]
        run: |
          uv run ruff check ./orionis/failure/ --statistics
          uv run python -B reactor test --start-dir="tests/failure" --verbosity=1 --fail-fast=1

      - name: 📁 Run Tests File [tests/file]
        run: |
          uv run ruff check ./orionis/file/ --statistics
          uv run python -B reactor test --start-dir="tests/file" --verbosity=1 --fail-fast=1

      - name: ✨ Run Tests Inspirational [tests/inspirational]
        run: |
          uv run ruff check ./orionis/inspirational/ --statistics
          uv run python -B reactor test --start-dir="tests/inspirational" --verbosity=1 --fail-fast=1

      - name: 🔎 Run Tests Introspection [tests/introspection]
        run: |
          uv run ruff check ./orionis/introspection/ --statistics
          uv run python -B reactor test --start-dir="tests/introspection" --verbosity=1 --fail-fast=1

      - name: 📋 Run Tests Log [tests/log]
        run: |
          uv run ruff check ./orionis/log/ --statistics
          uv run python -B reactor test --start-dir="tests/log" --verbosity=1 --fail-fast=1

      - name: 🔖 Run Tests Metadata [tests/metadata]
        run: |
          uv run ruff check ./orionis/metadata/ --statistics
          uv run python -B reactor test --start-dir="tests/metadata" --verbosity=1 --fail-fast=1

      - name: 📐 Run Tests Schemas [tests/schemas]
        run: |
          uv run ruff check ./orionis/schemas/ --statistics
          uv run python -B reactor test --start-dir="tests/schemas" --verbosity=1 --fail-fast=1

      - name: 🗂️ Run Tests Session [tests/session]
        run: |
          uv run ruff check ./orionis/session/ --statistics
          uv run python -B reactor test --start-dir="tests/session" --verbosity=1 --fail-fast=1

      - name: 🛠️ Run Tests Support [tests/support]
        run: |
          uv run ruff check ./orionis/support/ --statistics
          uv run python -B reactor test --start-dir="tests/support" --verbosity=1 --fail-fast=1

      - name: 🖥️ Run Tests System [tests/system]
        run: |
          uv run ruff check ./orionis/system/ --statistics
          uv run python -B reactor test --start-dir="tests/system" --verbosity=1 --fail-fast=1

      - name: 🧪 Run Tests Test [tests/test]
        run: |
          uv run ruff check ./orionis/test/ --statistics
          uv run python -B reactor test --start-dir="tests/test" --verbosity=1 --fail-fast=1

      - name: 🧪 Running Tests with Uncontrolled Console Outputs
        run: |
          uv run python -B reactor test --file-pattern="excl_*.py" --verbosity=1 --fail-fast=1

      - name: 🔎 Review Remaining Files
        run: |
          uv run ruff check ./orionis/database/ --statistics
          uv run ruff check ./orionis/foundation/ --statistics
          uv run ruff check ./orionis/http/ --statistics
