from orionis.test.cases.asynchronous import AsyncTestCase
from orionis.console.args.argument import CLIArgument
from orionis.console.enums.actions import ArgumentAction
from orionis.console.exceptions import CLIOrionisValueError

class TestCLIArgument(AsyncTestCase):

    async def testValidArgument(self):
        """
        Test creation of a valid CLIArgument instance.

        Ensures that a CLIArgument with typical valid parameters is correctly initialized.

        Returns
        -------
        None
        """
        arg = CLIArgument(flags=["--export", "-e"], type=str, help="Export file")
        self.assertEqual(arg.flags, ["--export", "-e"])
        self.assertEqual(arg.type, str)
        self.assertEqual(arg.help, "Export file")
        self.assertEqual(arg.action, ArgumentAction.STORE.value)

    async def testInvalidFlags(self):
        """
        Test that CLIArgument raises an error with invalid flags.

        Checks that providing an empty flags list raises CLIOrionisValueError.

        Returns
        -------
        None
        """
        with self.assertRaises(CLIOrionisValueError):
            CLIArgument(flags=[], type=str)

    async def testDefaultValue(self):
        """
        Test default value assignment in CLIArgument.

        Verifies that the default value is set and returned correctly.

        Returns
        -------
        None
        """
        arg = CLIArgument(flags=["--count"], type=int, default=5)
        self.assertEqual(arg.default, 5)

    async def testTypeValidation(self):
        """
        Test type validation for choices in CLIArgument.

        Ensures that all choices must match the specified type, otherwise an error is raised.

        Returns
        -------
        None
        """
        with self.assertRaises(CLIOrionisValueError):
            CLIArgument(flags=["--mode"], type=int, choices=[1, "two", 3])

    async def testBooleanFlag(self):
        """
        Test boolean flag auto-configuration.

        Checks that a boolean type flag is auto-configured with the correct action and type.

        Returns
        -------
        None
        """
        arg = CLIArgument(flags=["--force"], type=bool, default=False)
        self.assertEqual(arg.action, ArgumentAction.STORE_TRUE.value)
        self.assertIsNone(arg.type)

    async def testListArgument(self):
        """
        Test list type argument configuration.

        Ensures that a list type argument is configured with nargs and type as str for argparse compatibility.

        Returns
        -------
        None
        """
        arg = CLIArgument(flags=["--items"], type=list)
        self.assertEqual(arg.nargs, "+")
        self.assertEqual(arg.type, str)

    async def testEdgeCaseDuplicateFlags(self):
        """
        Test that duplicate flags raise an error.

        Ensures that providing duplicate flags in the flags list raises CLIOrionisValueError.

        Returns
        -------
        None
        """
        with self.assertRaises(CLIOrionisValueError):
            CLIArgument(flags=["--foo", "--foo"], type=str)

    async def testInvalidType(self):
        """
        Test that an invalid type raises an error.

        Ensures that providing a non-type object as type raises CLIOrionisValueError.

        Returns
        -------
        None
        """
        with self.assertRaises(CLIOrionisValueError):
            CLIArgument(flags=["--bar"], type="not_a_type")

    async def testAutoGeneratedHelpAndMetavar(self):
        """
        Test auto-generation of help and metavar fields.

        Ensures that help and metavar are auto-generated when not provided.

        Returns
        -------
        None
        """
        arg = CLIArgument(flags=["--long-flag"], type=str)
        self.assertTrue(arg.help.startswith("Long Flag"))
        self.assertEqual(arg.metavar, "LONG_FLAG")